version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          name: install
          command: python setup.py install
      - python/save-cache


workflows:
  main:
    jobs:
      - build-and-test
          filters:
            tags:
              only: /.*/
